environment                      = "dev"
bu_name                          = "it"
cloud_code                       = "az"
project_name                     = "da"
pri_location                     = "eastus"
